import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Headers";
import { SolanaProvider } from "./solanaProvider";
import { Providers } from "./wagmiProvider";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <SolanaProvider>
          <body
            className={`${inter.variable} antialiased`}
          >
            <Header />
            <main className="mx-auto w-full max-w-6xl px-4 py-6">{children}</main>
          </body>
        </SolanaProvider>
      </Providers>
    </html>
  );
}
